2023-04-04 03:27:24,977 - grteamxaridbot.logger - INFO - [ID = 1039515] [status = 500]
2023-04-04 03:27:26,286 - grteamxaridbot.logger - INFO - [ID = 1039516] [status = 500]
2023-04-04 03:27:29,140 - grteamxaridbot.logger - INFO - [ID = 1039518] [status = 500]
2023-04-04 03:27:30,402 - grteamxaridbot.logger - INFO - [ID = 1039519] [status = 500]
2023-04-04 03:27:34,847 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 14
2023-04-04 03:27:34,850 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/home/user/code/git/current/grteamxaridbot/grteamxaridbot/__main__.py", line 24, in parse_command
    parse_uzex(message)
  File "/home/user/code/git/current/grteamxaridbot/grteamxaridbot/core/telegram.py", line 51, in parse_uzex
    XaridUzex(message, message.text.split()[1], message.text.split()[2])
  File "/home/user/code/git/current/grteamxaridbot/grteamxaridbot/core/xarid_uzex_parse.py", line 38, in __init__
    self.__parse()
  File "/home/user/code/git/current/grteamxaridbot/grteamxaridbot/core/xarid_uzex_parse.py", line 61, in __parse
    bot.send_document(chat_id=self.message.chat.id, document=data, caption="@gr_team_xarid_bot")
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/__init__.py", line 2082, in send_document
    apihelper.send_data(
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/apihelper.py", line 940, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/user/.cache/pypoetry/virtualenvs/grteamxaridbot-pDIyDJ_m-py3.10/lib/python3.10/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 14

2023-04-04 03:28:17,368 - TeleBot - ERROR - Infinity polling: polling exited
2023-04-04 03:28:17,369 - TeleBot - ERROR - Break infinity polling
